export const metadata = {
  title: "Scroll Motion Value",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return <main>{children}</main>;
  // return <main>{children}</main>;
}
